"""add cooldown_until to nudge_log

Revision ID: ce55dc92105e
Revises: 76ab0714f3d1
Create Date: 2026-07-21 21:45:21.048160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce55dc92105e'
down_revision: Union[str, Sequence[str], None] = '76ab0714f3d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nudge_log', sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nudge_log', 'cooldown_until')
    # ### end Alembic commands ###
